# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json


site_name: Guia Digital do Classicista dos Trópicos
repo_name: bcdavasconcelos/gdct_mkdocs
repo_url: https://github.com/bcdavasconcelos/gdct_mkdocs
copyright: Copyright &copy; 2022 Guia Digital do Classicista dos Trópicos
site_description: >-
  O GDCT é um acervo de ferramentas e estratégias para auxiliar o trabalho de pesquisa nas ciências humanas, com atenção especial aos estudos antigos.
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
theme:
  name: material
  language: pt
  font:
    text: Alegreya
    code: Inconsolata
  favicon: assets/favicon.png
  icon:
    logo: logo
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - content.code.annotate
  - content.tooltips
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  # - navigation.prune
  # - navigation.tabs.sticky
  # - toc.integrate
plugins:
  - search:
      lang: pt
  - git-revision-date-localized
  - redirects:
      redirect_maps:
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: bcdavasconcelos
      repo: gdct_mkdocs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
    - Home: index.md
    - About: about.md
