# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Site info
site_name: Guia Digital do Classicista dos Trópicos
copyright: Copyright &copy; 2022 Guia Digital do Classicista dos Trópicos
site_description: >-
  O GDCT é um acervo de ferramentas e estratégias para auxiliar o trabalho de pesquisa nas ciências humanas, com atenção especial aos estudos antigos.

# Git config
repo_name: bcdavasconcelos/gdct_mkdocs
repo_url: https://github.com/bcdavasconcelos/gdct_mkdocs
edit_uri: edit/main/docs/

#extra:
#  analytics:
#    provider: google
#    property: G-XXXXXXXXXX
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  language: pt-BR
  font:
    text: Alegreya
    code: Inconsolata
  favicon: assets/favicon.png
  icon:
#    logo: bootstrap/terminal
#    logo: bootstrap/braces-asterisk
    logo: bootstrap/globe
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - content.code.annotate
  - content.tooltips
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - content.tabs.link
  # - header.autohide
  # - navigation.expand
  # - navigation.prune
  # - navigation.tabs.sticky
  # - toc.integrate
plugins:
  - ezlinks
  - search:
      lang: pt
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: iso_date
      locale: pt
      timezone: America/Sao_Paulo
  - redirects:
      redirect_maps:
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: bcdavasconcelos
      repo: gdct_mkdocs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
nav:
    - Home: index.md
    - Tags: tags.md
    - Sobre:
      - about/index.md
      - Material Theme: about/material.md
